            # Nato allied countries
            - AL # Albania
            - BE # Belgium
            - BG # Bulgaria
            - CN # Canada
            - HR # Croata
            - CZ # Czech Republic
            - DK # Denmark
            - EE # Estonia
            - FI # Finland
            - FR # France
            - DE # Germany
            - GR # Greece
            - HU # Hungary
            - IS # Iceland
            - IT # Italy
            - LV # Latvia
            - LT # Lithuania
            - LU # Luxembourgh
            - ME # Montenegro
            - NL # Netherlands
            - MK # North Macedonia
            - NO # Norway
            - PL # Poland
            - PT # Portugal
            - RO # Romania
            - SK # Slovakia
            - SI # Slovenia
            - ES # Spain
            - SE # Sweden
            - TR # Turkey
            - GB # United Kingdom
            - US # United States
