########################### NETWORKS
networks:
  vaultwarden_default:
    external: true

########################### SERVICES
services:
  newt:
    image: fosrl/newt
    container_name: dmz-information-newt
    restart: always
    hostname: dmz-information-newt
    networks:
      - vaultwarden_default
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.example.com
      - NEWT_ID=$NEWT_ID
      - NEWT_SECRET=$NEWT_SECRET
