########################### NETWORKS
networks:
  authentik:
  vaultwarden:

########################### SERVICES
services:
  newt:
    image: fosrl/newt
    container_name: newt-$HOSTNAME
    restart: always
    networks:
      - authentik_default
    environment:
      - PANGOLIN_ENDPOINT: $PANGOLIN_ENDPOINT
      - NEWT_ID: $NEWT_ID
      - NEWT_SECRET: $NEWT_SECRET
