########################### SECRETS
secrets:
  basic_auth_credentials:
    file: $CONTAINERDIR/secrets/newt

########################### NETWORKS
networks:
  vaultwarden_default:
    external: true

########################### SERVICES
services:
  newt:
    image: fosrl/newt
    container_name: dev_newt
    restart: always
    hostname: pangolin
    networks:
      - vaultwarden_default
    secrets:
      - NEWT_ID
      - NEWT_SECRET
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.example.com
      - NEWT_ID_FILE=/run/secrets/NEWT_ID
      - NEWT_SECRET=/run/secrets/NEWT_SECRET
