########################### SERVICES
services:
  newt:
    image: fosrl/newt
    container_name: dev_newt
    restart: unless-stopped
    hostname: pangolin
    networks:
      - vaultwarden
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.example.com
      - NEWT_ID=$SECRET_ID
      - NEWT_SECRET=$SECRET_SECRET
