########################### SECRETS
secrets:
  basic_auth_credentials:
    file: $DOCKERDIR/secrets/newt

########################### SERVICES
services:
  newt:
    image: fosrl/newt
    container_name: dev_newt
    restart: unless-stopped
    hostname: pangolin
    networks:
      - vaultwarden_default
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.example.com
      - NEWT_ID=$NEWT_ID
      - NEWT_SECRET=$NEWT_SECRET
