########################### SECRETS
secrets:
  basic_auth_credentials:
    file: $CONTAINERDIR/secrets/newt

########################### NETWORKS
networks:
  vaultwarden_default:
    external: true

########################### SERVICES
services:
  newt:
    image: fosrl/newt
    container_name: dev_newt
    restart: always
    hostname: pangolin
    networks:
      - vaultwarden_default
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.example.com
      - NEWT_ID=$NEWT_ID
      - NEWT_SECRET=$NEWT_SECRET
