########################### SECRETS
secrets:
  basic_auth_credentials:
    file: $DOCKERDIR/secrets/admin

########################### SERVICES
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    env_file:
      - /opt/containers/.env
      - ./.env
    hostname: vaultwarden
    networks:
      vaultwarden:
        ports: '80:80'
    environment:
      DOMAIN: "https://b.example.com"
      ADMIN_TOKEN: admin_token
    volumes:
      - ./appdata/data/:/data/
