########################### NETWORKS
networks:
  vaultwarden:

########################### SERVICES
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    ports:
      - '80:80'
    environment:
      PUID: $PUID
      GUID: $PGID
      DOMAIN: $DOMAIN
      # Generating ADMIN_TOKEN - https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page
      ADMIN_TOKEN: $ADMIN_TOKEN
      SIGNUPS_ALLOWED: false
      SHOW_PASSWORD_HINT: false
      # Email settings - https://github.com/dani-garcia/vaultwarden/wiki/SMTP-Configuration
      SMTP_HOST: $SMTP_HOST
      SMTP_FROM: $SMTP_FROM
      SMTP_PORT: $SMTP_PORT
      SMTP_SECURITY: $SMTP_SECURITY
      SMTP_USERNAME: $SMTP_USERNAME
      SMTP_PASSWORD: $SMTP_PASSWORD
      # Mobile Push Notifications (Auto syncing vault) - https://github.com/dani-garcia/vaultwarden/wiki/Enabling-Mobile-Client-push-notification
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: $PUSH_INSTALLATION_ID
      PUSH_INSTALLATION_KEY: $PUSH_INSTALLATION_KEY
      # EU settings
      PUSH_RELAY_URI: 'https://api.bitwarden.eu'
      PUSH_IDENTITY_URI: 'https://identity.bitwarden.eu'
    volumes:
      - $CONTAINERDIR/appdata/data/:/data/
